on: [push]
jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm ci
    - run: npx playwright install-deps
    - run: npx playwright install
    - run: npx playwright test
